import { Inter } from "next/font/google";
// import storeWrapper from "@/app/redux/reduxStore";
// import useLoadUserData from "@/app/hooks/LoadUserData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const { store, props } = storeWrapper.useWrappedStore(rest);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position="bottom-left" reverseOrder={false} />
      </body>
    </html>
  );
}
